const data = {
'Abbey Wood' : 'ABW',
'Aber' : 'ABE',
'Abercynon' : 'ACY',
'Aberdare' : 'ABA',
'Aberdeen' : 'ABD',
'Aberdour' : 'AUR',
'Aberdovey' : 'AVY',
'Abererch' : 'ABH',
'Abergavenny' : 'AGV',
'Abergele & Pensarn' : 'AGL',
'Aberystwyth' : 'AYW',
'Accrington' : 'ACR',
'Achanalt' : 'AAT',
'Achnasheen' : 'ACN',
'Achnashellach' : 'ACH',
'Acklington' : 'ACK',
'Acle' : 'ACL',
'Acocks Green' : 'ACG',
'Acton Bridge (Cheshire)' : 'ACB',
'Acton Central' : 'ACC',
'Acton Main Line' : 'AML',
'Adderley Park' : 'ADD',
'Addiewell' : 'ADW',
'Addlestone' : 'ASN',
'Adisham' : 'ADM',
'Adlington (Cheshire)' : 'ADC',
'Adlington (Lancs)' : 'ADL',
'Adwick' : 'AWK',
'Aigburth' : 'AIG',
'Ainsdale' : 'ANS',
'Aintree' : 'AIN',
'Airbles' : 'AIR',
'Airdrie' : 'ADR',
'Albany Park' : 'AYP',
'Albrighton' : 'ALB',
'Alderley Edge' : 'ALD',
'Aldermaston' : 'AMT',
'Aldershot' : 'AHT',
'Aldrington' : 'AGT',
'Alexandra Palace' : 'AAP',
'Alexandra Parade' : 'AXP',
'Alexandria' : 'ALX',
'Alfreton' : 'ALF',
'Allens West' : 'ALW',
'Alloa' : 'ALO',
'Alness' : 'ASS',
'Alnmouth' : 'ALM',
'Alresford (Essex)' : 'ALR',
'Alsager' : 'ASG',
'Althorne (Essex)' : 'ALN',
'Althorpe' : 'ALP',
'Altnabreac' : 'ABC',
'Alton' : 'AON',
'Altrincham' : 'ALT',
'Alvechurch' : 'ALV',
'Ambergate' : 'AMB',
'Amberley' : 'AMY',
'Amersham' : 'AMR',
'Ammanford' : 'AMF',
'Ancaster' : 'ANC',
'Anderston' : 'AND',
'Andover' : 'ADV',
'Anerley' : 'ANZ',
'Angmering' : 'ANG',
'Annan' : 'ANN',
'Anniesland' : 'ANL',
'Ansdell & Fairhaven' : 'AFV',
'Apperley Bridge' : 'APY',
'Appleby' : 'APP',
'Appledore (Kent)' : 'APD',
'Appleford' : 'APF',
'Appley Bridge' : 'APB',
'Apsley' : 'APS',
'Arbroath' : 'ARB',
'Ardgay' : 'ARD',
'Ardlui' : 'AUI',
'Ardrossan Harbour' : 'ADS',
'Ardrossan South Beach' : 'ASB',
'Ardrossan Town' : 'ADN',
'Ardwick' : 'ADK',
'Argyle Street' : 'AGS',
'Arisaig' : 'ARG',
'Arlesey' : 'ARL',
'Armadale (West Lothian)' : 'ARM',
'Armathwaite' : 'AWT',
'Arnside' : 'ARN',
'Arram' : 'ARR',
'Arrochar & Tarbet' : 'ART',
'Arundel' : 'ARU',
'Ascot (Berks)' : 'ACT',
'Ascott-under-Wychwood' : 'AUW',
'Ash' : 'ASH',
'Ash Vale' : 'AHV',
'Ashburys' : 'ABY',
'Ashchurch for Tewkesbury' : 'ASC',
'Ashfield' : 'ASF',
'Ashford (Surrey)' : 'AFS',
'Ashford International' : 'AFK',
'Ashford International (Eurostar)' : 'ASI',
'Ashley' : 'ASY',
'Ashtead' : 'AHD',
'Ashton-under-Lyne' : 'AHN',
'Ashurst (Kent)' : 'AHS',
'Ashurst New Forest' : 'ANF',
'Ashwell & Morden' : 'AWM',
'Askam' : 'ASK',
'Aslockton' : 'ALK',
'Aspatria' : 'ASP',
'Aspley Guise' : 'APG',
'Aston' : 'AST',
'Atherstone' : 'ATH',
'Atherton' : 'ATN',
'Attadale' : 'ATT',
'Attenborough' : 'ATB',
'Attleborough' : 'ATL',
'Auchinleck' : 'AUK',
'Audley End' : 'AUD',
'Aughton Park' : 'AUG',
'Aviemore' : 'AVM',
'Avoncliff' : 'AVF',
'Avonmouth' : 'AVN',
'Axminster' : 'AXM',
'Aylesbury' : 'AYS',
'Aylesbury Vale Parkway' : 'AVP',
'Aylesford' : 'AYL',
'Aylesham' : 'AYH',
'Ayr' : 'AYR',
'Bache' : 'BAC',
'Baglan' : 'BAJ',
'Bagshot' : 'BAG',
'Baildon' : 'BLD',
'Baillieston' : 'BIO',
'Balcombe' : 'BAB',
'Baldock' : 'BDK',
'Balham' : 'BAL',
'Balloch' : 'BHC',
'Balmossie' : 'BSI',
'Bamber Bridge' : 'BMB',
'Bamford' : 'BAM',
'Banavie' : 'BNV',
'Banbury' : 'BAN',
'Bangor (Gwynedd)' : 'BNG',
'Bank Hall' : 'BAH',
'Banstead' : 'BAD',
'Barassie' : 'BSS',
'Barbican' : 'ZBB',
'Bardon Mill' : 'BLL',
'Bare Lane' : 'BAR',
'Bargeddie' : 'BGI',
'Bargoed' : 'BGD',
'Barking' : 'BKG',
'Barlaston' : 'BRT',
'Barming' : 'BMG',
'Barmouth' : 'BRM',
'Barnehurst' : 'BNH',
'Barnes' : 'BNS',
'Barnes Bridge' : 'BNI',
'Barnetby' : 'BTB',
'Barnham' : 'BAA',
'Barnhill' : 'BNL',
'Barnsley' : 'BNY',
'Barnstaple' : 'BNP',
'Barnt Green' : 'BTG',
'Barrhead' : 'BRR',
'Barrhill' : 'BRL',
'Barrow Haven' : 'BAV',
'Barrow-in-Furness' : 'BIF',
'Barrow-Upon-Soar' : 'BWS',
'Barry' : 'BRY',
'Barry Docks' : 'BYD',
'Barry Island' : 'BYI',
'Barry Links' : 'BYL',
'Barton-on-Humber' : 'BAU',
'Basildon' : 'BSO',
'Basingstoke' : 'BSK',
'Bat & Ball' : 'BBL',
'Bath Spa' : 'BTH',
'Bathgate' : 'BHG',
'Batley' : 'BTL',
'Battersby' : 'BTT',
'Battersea Park' : 'BAK',
'Battle' : 'BAT',
'Battlesbridge' : 'BLB',
'Bayford' : 'BAY',
'Beaconsfield' : 'BCF',
'Bearley' : 'BER',
'Bearsden' : 'BRN',
'Bearsted' : 'BSD',
'Beasdale' : 'BSL',
'Beaulieu Road' : 'BEU',
'Beauly' : 'BEL',
'Bebington' : 'BEB',
'Beccles' : 'BCC',
'Beckenham Hill' : 'BEC',
'Beckenham Junction' : 'BKJ',
'Bedford' : 'BDM',
'Bedford St Johns' : 'BSJ',
'Bedhampton' : 'BDH',
'Bedminster' : 'BMT',
'Bedworth' : 'BEH',
'Bedwyn' : 'BDW',
'Beeston' : 'BEE',
'Bekesbourne' : 'BKS',
'Belle Vue' : 'BLV',
'Bellgrove' : 'BLG',
'Bellingham' : 'BGM',
'Bellshill' : 'BLH',
'Belmont' : 'BLM',
'Belper' : 'BLP',
'Beltring' : 'BEG',
'Belvedere' : 'BVD',
'Bempton' : 'BEM',
'Ben Rhydding' : 'BEY',
'Benfleet' : 'BEF',
'Bentham' : 'BEN',
'Bentley (Hants)' : 'BTY',
'Bentley (South Yorks)' : 'BYK',
'Bere Alston' : 'BAS',
'Bere Ferrers' : 'BFE',
'Berkhamsted' : 'BKM',
'Berkswell' : 'BKW',
'Bermuda Park' : 'BEP',
'Berney Arms' : 'BYA',
'Berry Brow' : 'BBW',
'Berrylands' : 'BRS',
'Berwick (Sussex)' : 'BRK',
'Berwick-upon-Tweed' : 'BWK',
'Bescar Lane' : 'BES',
'Bescot Stadium' : 'BSC',
'Betchworth' : 'BTO',
'Bethnal Green' : 'BET',
'Betws-y-Coed' : 'BYC',
'Beverley' : 'BEV',
'Bexhill' : 'BEX',
'Bexley' : 'BXY',
'Bexleyheath' : 'BXH',
'Bicester North' : 'BCS',
'Bicester Village' : 'BIT',
'Bickley' : 'BKL',
'Bidston' : 'BID',
'Biggleswade' : 'BIW',
'Bilbrook' : 'BBK',
'Billericay' : 'BIC',
'Billingham (Cleveland)' : 'BIL',
'Billingshurst' : 'BIG',
'Bingham' : 'BIN',
'Bingley' : 'BIY',
'Birchgrove' : 'BCG',
'Birchington-on-sea' : 'BCH',
'Birchwood' : 'BWD',
'Birkbeck' : 'BIK',
'Birkdale' : 'BDL',
'Birkenhead Central' : 'BKC',
'Birkenhead Hamilton Square' : 'BKQ',
'Birkenhead North' : 'BKN',
'Birkenhead Park' : 'BKP',
'Birmingham International' : 'BHI',
'Birmingham Moor Street' : 'BMO',
'Birmingham New Street' : 'BHM',
'Birmingham Snow Hill' : 'BSW',
'Bishop Auckland' : 'BIA',
'Bishopbriggs' : 'BBG',
'Bishops Stortford' : 'BIS',
'Bishopstone (Sussex)' : 'BIP',
'Bishopton (Strathclyde)' : 'BPT',
'Bitterne' : 'BTE',
'Blackburn' : 'BBN',
'Blackheath' : 'BKH',
'Blackhorse Road' : 'BHO',
'Blackpool North' : 'BPN',
'Blackpool Pleasure Beach' : 'BPB',
'Blackpool South' : 'BPS',
'Blackridge' : 'BKR',
'Blackrod' : 'BLK',
'Blackwater' : 'BAW',
'Blaenau Ffestiniog' : 'BFF',
'Blair Atholl' : 'BLA',
'Blairhill' : 'BAI',
'Blake Street' : 'BKT',
'Blakedown' : 'BKD',
'Blantyre' : 'BLT',
'Blaydon' : 'BLO',
'Bleasby' : 'BSB',
'Bletchley' : 'BLY',
'Bloxwich' : 'BLX',
'Bloxwich North' : 'BWN',
'Blundellsands & Crosby' : 'BLN',
'Blythe Bridge' : 'BYB',
'Bodmin Parkway' : 'BOD',
'Bodorgan' : 'BOR',
'Bognor Regis' : 'BOG',
'Bogston' : 'BGS',
'Bolton' : 'BON',
'Bolton-Upon-Dearne' : 'BTD',
'Bookham' : 'BKA',
'Bootle (Cumbria)' : 'BOC',
'Bootle New Strand' : 'BNW',
'Bootle Oriel Road' : 'BOT',
'Bordesley' : 'BBS',
'Borough Green & Wrotham' : 'BRG',
'Borth' : 'BRH',
'Bosham' : 'BOH',
'Boston' : 'BSN',
'Botley' : 'BOE',
'Bottesford' : 'BTF',
'Bourne End' : 'BNE',
'Bournemouth' : 'BMH',
'Bournville' : 'BRV',
'Bow Brickhill' : 'BWB',
'Bowes Park' : 'BOP',
'Bowling' : 'BWG',
'Box Hill & Westhumble' : 'BXW',
'Bracknell' : 'BCE',
'Bradford Forster Square' : 'BDQ',
'Bradford Interchange' : 'BDI',
'Bradford-on-Avon' : 'BOA',
'Brading' : 'BDN',
'Braintree' : 'BTR',
'Braintree Freeport' : 'BTP',
'Bramhall' : 'BML',
'Bramley (Hants)' : 'BMY',
'Bramley (W Yorks)' : 'BLE',
'Brampton (Cumbria)' : 'BMP',
'Brampton (Suffolk)' : 'BRP',
'Branchton' : 'BCN',
'Brandon' : 'BND',
'Branksome' : 'BSM',
'Braystones (Cumbria)' : 'BYS',
'Bredbury' : 'BDY',
'Breich' : 'BRC',
'Brentford' : 'BFD',
'Brentwood' : 'BRE',
'Bricket Wood' : 'BWO',
'Bridge of Allan' : 'BEA',
'Bridge of Orchy' : 'BRO',
'Bridgend' : 'BGN',
'Bridgeton' : 'BDG',
'Bridgwater' : 'BWT',
'Bridlington' : 'BDT',
'Brierfield' : 'BRF',
'Brigg' : 'BGG',
'Brighouse' : 'BGH',
'Brighton (East Sussex)' : 'BTN',
'Brimsdown' : 'BMD',
'Brinnington' : 'BNT',
'Bristol Parkway' : 'BPW',
'Bristol Temple Meads' : 'BRI',
'Brithdir' : 'BHD',
'Briton Ferry' : 'BNF',
'Brixton' : 'BRX',
'Broad Green' : 'BGE',
'Broadbottom' : 'BDB',
'Broadstairs' : 'BSR',
'Brockenhurst' : 'BCU',
'Brockholes' : 'BHS',
'Brockley' : 'BCY',
'Bromborough' : 'BOM',
'Bromborough Rake' : 'BMR',
'Bromley Cross (Lancs)' : 'BMC',
'Bromley North' : 'BMN',
'Bromley South' : 'BMS',
'Bromsgrove' : 'BMV',
'Brondesbury' : 'BSY',
'Brondesbury Park' : 'BSP',
'Brookmans Park' : 'BPK',
'Brookwood' : 'BKO',
'Broome' : 'BME',
'Broomfleet' : 'BMF',
'Brora' : 'BRA',
'Brough' : 'BUH',
'Broughty Ferry' : 'BYF',
'Broxbourne' : 'BXB',
'Bruce Grove' : 'BCV',
'Brundall' : 'BDA',
'Brundall Gardens' : 'BGA',
'Brunstane' : 'BSU',
'Brunswick' : 'BRW',
'Bruton' : 'BRU',
'Bryn' : 'BYN',
'Buckenham (Norfolk)' : 'BUC',
'Buckley' : 'BCK',
'Bucknell' : 'BUK',
'Buckshaw Parkway' : 'BSV',
'Bugle' : 'BGL',
'Builth Road' : 'BHR',
'Bulwell' : 'BLW',
'Bures' : 'BUE',
'Burgess Hill' : 'BUG',
'Burley Park' : 'BUY',
'Burley-in-Wharfedale' : 'BUW',
'Burnage' : 'BNA',
'Burneside (Cumbria)' : 'BUD',
'Burnham (Bucks)' : 'BNM',
'Burnham-on-Crouch' : 'BUU',
'Burnley Barracks' : 'BUB',
'Burnley Central' : 'BNC',
'Burnley Manchester Road' : 'BYM',
'Burnside (Strathclyde)' : 'BUI',
'Burntisland' : 'BTS',
'Burscough Bridge' : 'BCB',
'Burscough Junction' : 'BCJ',
'Bursledon' : 'BUO',
'Burton Joyce' : 'BUJ',
'Burton-on-Trent' : 'BUT',
'Bury St Edmunds' : 'BSE',
'Busby' : 'BUS',
'Bush Hill Park' : 'BHK',
'Bushey' : 'BSH',
'Butlers Lane' : 'BUL',
'Buxted' : 'BXD',
'Buxton' : 'BUX',
'Byfleet & New Haw' : 'BFN',
'Bynea' : 'BYE',
'Cadoxton' : 'CAD',
'Caergwrle' : 'CGW',
'Caerphilly' : 'CPH',
'Caersws' : 'CWS',
'Caldercruix' : 'CAC',
'Caldicot' : 'CDT',
'Caledonian Rd & Barnsbury' : 'CIR',
'Calstock' : 'CSK',
'Cam & Dursley' : 'CDU',
'Camberley' : 'CAM',
'Camborne' : 'CBN',
'Cambridge' : 'CBG',
'Cambridge Heath' : 'CBH',
'Cambridge North' : 'CMB',
'Cambuslang' : 'CBL',
'Camden Road' : 'CMD',
'Camelon' : 'CMO',
'Canada Water' : 'ZCW',
'Canley' : 'CNL',
'Cannock' : 'CAO',
'Canonbury' : 'CNN',
'Canterbury East' : 'CBE',
'Canterbury West' : 'CBW',
'Cantley' : 'CNY',
'Capenhurst' : 'CPU',
'Carbis Bay' : 'CBB',
'Cardenden' : 'CDD',
'Cardiff Bay' : 'CDB',
'Cardiff Central' : 'CDF',
'Cardiff Queen Street' : 'CDQ',
'Cardonald' : 'CDO',
'Cardross' : 'CDR',
'Carfin' : 'CRF',
'Cark & Cartmel' : 'CAK',
'Carlisle' : 'CAR',
'Carlton' : 'CTO',
'Carluke' : 'CLU',
'Carmarthen' : 'CMN',
'Carmyle' : 'CML',
'Carnforth' : 'CNF',
'Carnoustie' : 'CAN',
'Carntyne' : 'CAY',
'Carpenders Park' : 'CPK',
'Carrbridge' : 'CAG',
'Carshalton' : 'CSH',
'Carshalton Beeches' : 'CSB',
'Carstairs' : 'CRS',
'Cartsdyke' : 'CDY',
'Castle Bar Park' : 'CBP',
'Castle Cary' : 'CLC',
'Castleford' : 'CFD',
'Castleton (Manchester)' : 'CAS',
'Castleton Moor' : 'CSM',
'Caterham' : 'CAT',
'Catford' : 'CTF',
'Catford Bridge Rail Station' : 'CFB',
'Cathays' : 'CYS',
'Cathcart' : 'CCT',
'Cattal' : 'CTL',
'Causeland' : 'CAU',
'Cefn-y-Bedd' : 'CYB',
'Chadwell Heath' : 'CTH',
'Chafford Hundred Lakeside' : 'CFH',
'Chalfont & Latimer' : 'CFO',
'Chalkwell' : 'CHW',
'Chandlers Ford' : 'CFR',
'Chapel-en-le-Frith' : 'CEF',
'Chapelton (Devon)' : 'CPN',
'Chapeltown (South Yorks)' : 'CLN',
'Chappel & Wakes Colne' : 'CWC',
'Charing (Kent)' : 'CHG',
'Charing Cross (Glasgow)' : 'CHC',
'Charlbury' : 'CBY',
'Charlton' : 'CTN',
'Chartham' : 'CRT',
'Chassen Road' : 'CSR',
'Chatelherault' : 'CTE',
'Chatham' : 'CTM',
'Chathill' : 'CHT',
'Cheadle Hulme' : 'CHU',
'Cheam' : 'CHE',
'Cheddington' : 'CED',
'Chelford (Cheshire)' : 'CEL',
'Chelmsford' : 'CHM',
'Chelsfield' : 'CLD',
'Cheltenham Spa' : 'CNM',
'Chepstow' : 'CPW',
'Cherry Tree' : 'CYT',
'Chertsey' : 'CHY',
'Cheshunt' : 'CHN',
'Chessington North' : 'CSN',
'Chessington South' : 'CSS',
'Chester' : 'CTR',
'Chester Road' : 'CRD',
'Chesterfield' : 'CHD',
'Chester-le-Street' : 'CLS',
'Chestfield & Swalecliffe' : 'CSW',
'Chetnole' : 'CNO',
'Chichester' : 'CCH',
'Chilham' : 'CIL',
'Chilworth' : 'CHL',
'Chingford' : 'CHI',
'Chinley' : 'CLY',
'Chippenham' : 'CPM',
'Chipstead' : 'CHP',
'Chirk' : 'CRK',
'Chislehurst' : 'CIT',
'Chiswick' : 'CHK',
'Cholsey' : 'CHO',
'Chorley' : 'CRL',
'Chorleywood' : 'CLW',
'Christchurch' : 'CHR',
'Christs Hospital' : 'CHH',
'Church & Oswaldtwistle' : 'CTW',
'Church Fenton' : 'CHF',
'Church Stretton' : 'CTT',
'Cilmeri' : 'CIM',
'City Thameslink' : 'CTK',
'Clacton-on-Sea' : 'CLT',
'Clandon' : 'CLA',
'Clapham (North Yorkshire)' : 'CPY',
'Clapham High Street' : 'CLP',
'Clapham Junction' : 'CLJ',
'Clapton' : 'CPT',
'Clarbeston Road' : 'CLR',
'Clarkston' : 'CKS',
'Claverdon' : 'CLV',
'Claygate' : 'CLG',
'Cleethorpes' : 'CLE',
'Cleland' : 'CEA',
'Clifton (Manchester)' : 'CLI',
'Clifton Down' : 'CFN',
'Clitheroe' : 'CLH',
'Clock House' : 'CLK',
'Clunderwen' : 'CUW',
'Clydebank' : 'CYK',
'Coatbridge Central' : 'CBC',
'Coatbridge Sunnyside' : 'CBS',
'Coatdyke' : 'COA',
'Cobham & Stoke d\'Abernon' : 'CSD',
'Codsall' : 'CSL',
'Cogan' : 'CGN',
'Colchester' : 'COL',
'Colchester Town' : 'CET',
'Coleshill Parkway' : 'CEH',
'Collingham' : 'CLM',
'Collington' : 'CLL',
'Colne' : 'CNE',
'Colwall' : 'CWL',
'Colwyn Bay' : 'CWB',
'Combe (Oxon)' : 'CME',
'Commondale' : 'COM',
'Congleton' : 'CNG',
'Conisbrough' : 'CNS',
'Connel Ferry' : 'CON',
'Conon Bridge' : 'CBD',
'Cononley' : 'CEY',
'Conway Park' : 'CNP',
'Conwy' : 'CNW',
'Cooden Beach' : 'COB',
'Cookham' : 'COO',
'Cooksbridge' : 'CBR',
'Coombe Junction Halt' : 'COE',
'Copplestone' : 'COP',
'Corbridge' : 'CRB',
'Corby' : 'COR',
'Corfe Castle' : 'CFC',
'Corkerhill' : 'CKH',
'Corkickle' : 'CKL',
'Corpach' : 'CPA',
'Corrour' : 'CRR',
'Coryton' : 'COY',
'Coseley' : 'CSY',
'Cosford' : 'COS',
'Cosham' : 'CSA',
'Cottingham' : 'CGM',
'Cottingley' : 'COT',
'Coulsdon South' : 'CDS',
'Coulsdon Town' : 'CDN',
'Coventry' : 'COV',
'Coventry Arena' : 'CAA',
'Cowden (Kent)' : 'CWN',
'Cowdenbeath' : 'COW',
'Cradley Heath' : 'CRA',
'Craigendoran' : 'CGD',
'Cramlington' : 'CRM',
'Cranbrook (Devon)' : 'CBK',
'Craven Arms' : 'CRV',
'Crawley' : 'CRW',
'Crayford' : 'CRY',
'Crediton' : 'CDI',
'Cressing (Essex)' : 'CES',
'Cressington' : 'CSG',
'Creswell' : 'CWD',
'Crewe' : 'CRE',
'Crewkerne' : 'CKN',
'Crews Hill' : 'CWH',
'Crianlarich' : 'CNR',
'Criccieth' : 'CCC',
'Cricklewood' : 'CRI',
'Croftfoot' : 'CFF',
'Crofton Park' : 'CFT',
'Cromer' : 'CMR',
'Cromford' : 'CMF',
'Crookston' : 'CKT',
'Cross Gates' : 'CRG',
'Crossflatts' : 'CFL',
'Crosshill' : 'COI',
'Crosskeys' : 'CKY',
'Crossmyloof' : 'CMY',
'Croston' : 'CSO',
'Crouch Hill' : 'CRH',
'Crowborough' : 'COH',
'Crowhurst' : 'CWU',
'Crowle' : 'CWE',
'Crowthorne' : 'CRN',
'Croy' : 'CRO',
'Crystal Palace' : 'CYP',
'Cuddington' : 'CUD',
'Cuffley' : 'CUF',
'Culham' : 'CUM',
'Culrain' : 'CUA',
'Cumbernauld' : 'CUB',
'Cupar' : 'CUP',
'Curriehill' : 'CUH',
'Cuxton' : 'CUX',
'Cwmbach' : 'CMH',
'Cwmbran' : 'CWM',
'Cynghordy' : 'CYN',
'Dagenham Dock' : 'DDK',
'Daisy Hill' : 'DSY',
'Dalgety Bay' : 'DAG',
'Dalmally' : 'DAL',
'Dalmarnock' : 'DAK',
'Dalmeny' : 'DAM',
'Dalmuir' : 'DMR',
'Dalreoch' : 'DLR',
'Dalry' : 'DLY',
'Dalston (Cumbria)' : 'DLS',
'Dalston Junction' : 'DLJ',
'Dalston Kingsland' : 'DLK',
'Dalton (Cumbria)' : 'DLT',
'Dalwhinnie' : 'DLW',
'Danby' : 'DNY',
'Danescourt' : 'DCT',
'Danzey' : 'DZY',
'Darlington' : 'DAR',
'Darnall' : 'DAN',
'Darsham' : 'DSM',
'Dartford' : 'DFD',
'Darton' : 'DRT',
'Darwen' : 'DWN',
'Datchet' : 'DAT',
'Davenport' : 'DVN',
'Dawlish' : 'DWL',
'Dawlish Warren' : 'DWW',
'Deal' : 'DEA',
'Dean (Wilts)' : 'DEN',
'Deansgate' : 'DGT',
'Deganwy' : 'DGY',
'Deighton' : 'DHN',
'Delamere' : 'DLM',
'Denby Dale' : 'DBD',
'Denham' : 'DNM',
'Denham Golf Club' : 'DGC',
'Denmark Hill' : 'DMK',
'Dent' : 'DNT',
'Denton' : 'DTN',
'Deptford' : 'DEP',
'Derby' : 'DBY',
'Derby Road (Ipswich)' : 'DBR',
'Devonport (Devon)' : 'DPT',
'Devonport Dockyard' : 'DOC',
'Dewsbury' : 'DEW',
'Didcot Parkway' : 'DID',
'Digby & Sowton' : 'DIG',
'Dilton Marsh' : 'DMH',
'Dinas (Rhondda)' : 'DMG',
'Dinas Powys' : 'DNS',
'Dingle Road' : 'DGL',
'Dingwall' : 'DIN',
'Dinsdale' : 'DND',
'Dinting' : 'DTG',
'Disley' : 'DSL',
'Diss' : 'DIS',
'Dodworth' : 'DOD',
'Dolau' : 'DOL',
'Doleham' : 'DLH',
'Dolgarrog' : 'DLG',
'Dolwyddelan' : 'DWD',
'Doncaster' : 'DON',
'Dorchester South' : 'DCH',
'Dorchester West' : 'DCW',
'Dore & Totley' : 'DOR',
'Dorking (Main)' : 'DKG',
'Dorking Deepdene' : 'DPD',
'Dorking West' : 'DKT',
'Dormans' : 'DMS',
'Dorridge' : 'DDG',
'Dove Holes' : 'DVH',
'Dover Priory' : 'DVP',
'Dovercourt' : 'DVC',
'Dovey Junction' : 'DVY',
'Downham Market' : 'DOW',
'Drayton Green' : 'DRG',
'Drayton Park' : 'DYP',
'Drem' : 'DRM',
'Driffield' : 'DRF',
'Drigg' : 'DRI',
'Droitwich Spa' : 'DTW',
'Dronfield' : 'DRO',
'Drumchapel' : 'DMC',
'Drumfrochar' : 'DFR',
'Drumgelloch' : 'DRU',
'Drumry' : 'DMY',
'Dublin Ferryport' : 'DFP',
'Dublin Port - Stena' : 'DPS',
'Duddeston' : 'DUD',
'Dudley Port' : 'DDP',
'Duffield' : 'DFI',
'Duirinish' : 'DRN',
'Duke Street' : 'DST',
'Dullingham' : 'DUL',
'Dumbarton Central' : 'DBC',
'Dumbarton East' : 'DBE',
'Dumbreck' : 'DUM',
'Dumfries' : 'DMF',
'Dumpton Park' : 'DMP',
'Dunbar' : 'DUN',
'Dunblane' : 'DBL',
'Duncraig' : 'DCG',
'Dundee' : 'DEE',
'Dunfermline Queen Margaret' : 'DFL',
'Dunfermline Town' : 'DFE',
'Dunkeld & Birnam' : 'DKD',
'Dunlop' : 'DNL',
'Dunrobin Castle' : 'DNO',
'Dunston' : 'DOT',
'Dunton Green' : 'DNG',
'Durham' : 'DHM',
'Durrington-on-Sea' : 'DUR',
'Dyce' : 'DYC',
'Dyffryn Ardudwy' : 'DYF',
'Eaglescliffe' : 'EAG',
'Ealing Broadway' : 'EAL',
'Earlestown' : 'ERL',
'Earley' : 'EAR',
'Earlsfield' : 'EAD',
'Earlswood (Surrey)' : 'ELD',
'Earlswood (West Midlands)' : 'EWD',
'East Croydon' : 'ECR',
'East Didsbury' : 'EDY',
'East Dulwich' : 'EDW',
'East Farleigh' : 'EFL',
'East Garforth' : 'EGF',
'East Grinstead' : 'EGR',
'East Kilbride' : 'EKL',
'East Malling' : 'EML',
'East Midlands Parkway' : 'EMD',
'East Tilbury' : 'ETL',
'East Worthing' : 'EWR',
'Eastbourne' : 'EBN',
'Eastbrook' : 'EBK',
'Easterhouse' : 'EST',
'Eastham Rake' : 'ERA',
'Eastleigh' : 'ESL',
'Eastrington' : 'EGN',
'Ebbsfleet International' : 'EBD',
'Ebbw Vale Parkway' : 'EBV',
'Ebbw Vale Town' : 'EBB',
'Eccles (Manchester)' : 'ECC',
'Eccles Road' : 'ECS',
'Eccleston Park' : 'ECL',
'Edale' : 'EDL',
'Eden Park' : 'EDN',
'Edenbridge' : 'EBR',
'Edenbridge Town' : 'EBT',
'Edge Hill' : 'EDG',
'Edinburgh' : 'EDB',
'Edinburgh Gateway' : 'EGY',
'Edinburgh Park' : 'EDP',
'Edmonton Green' : 'EDR',
'Effingham Junction' : 'EFF',
'Eggesford' : 'EGG',
'Egham' : 'EGH',
'Egton' : 'EGT',
'Elephant & Castle' : 'EPH',
'Elephant & Castle (Underground)' : 'ZEL',
'Elgin' : 'ELG',
'Ellesmere Port' : 'ELP',
'Elmers End' : 'ELE',
'Elmstead Woods' : 'ESD',
'Elmswell' : 'ESW',
'Elsecar' : 'ELR',
'Elsenham (Essex)' : 'ESM',
'Elstree & Borehamwood' : 'ELS',
'Eltham' : 'ELW',
'Elton & Orston' : 'ELO',
'Ely' : 'ELY',
'Emerson Park' : 'EMP',
'Emsworth' : 'EMS',
'Energlyn & Churchill Park' : 'ECP',
'Enfield Chase' : 'ENC',
'Enfield Lock' : 'ENL',
'Enfield Town' : 'ENF',
'Entwistle' : 'ENT',
'Epsom (Surrey)' : 'EPS',
'Epsom Downs' : 'EPD',
'Erdington' : 'ERD',
'Eridge' : 'ERI',
'Erith' : 'ERH',
'Esher' : 'ESH',
'Eskbank' : 'EKB',
'Essex Road' : 'EXR',
'Etchingham' : 'ETC',
'Euxton Balshaw Lane' : 'EBA',
'Evesham' : 'EVE',
'Ewell East' : 'EWE',
'Ewell West' : 'EWW',
'Exeter Central' : 'EXC',
'Exeter St David\'s' : 'EXD',
'Exeter St Thomas' : 'EXT',
'Exhibition Centre (Glasgow)' : 'EXG',
'Exmouth' : 'EXM',
'Exton' : 'EXN',
'Eynsford' : 'EYN',
'Fairbourne' : 'FRB',
'Fairfield' : 'FRF',
'Fairlie' : 'FRL',
'Fairwater' : 'FRW',
'Falconwood' : 'FCN',
'Falkirk Grahamston' : 'FKG',
'Falkirk High' : 'FKK',
'Falls of Cruachan' : 'FOC',
'Falmer' : 'FMR',
'Falmouth Docks' : 'FAL',
'Falmouth Town' : 'FMT',
'Fareham' : 'FRM',
'Farnborough (Main)' : 'FNB',
'Farnborough North' : 'FNN',
'Farncombe' : 'FNC',
'Farnham' : 'FNH',
'Farningham Road' : 'FNR',
'Farnworth' : 'FNW',
'Farringdon' : 'ZFD',
'Fauldhouse' : 'FLD',
'Faversham' : 'FAV',
'Faygate' : 'FGT',
'Fazakerley' : 'FAZ',
'Fearn' : 'FRN',
'Featherstone' : 'FEA',
'Felixstowe' : 'FLX',
'Feltham' : 'FEL',
'Feniton' : 'FNT',
'Fenny Stratford' : 'FEN',
'Fernhill' : 'FER',
'Ferriby' : 'FRY',
'Ferryside' : 'FYS',
'Ffairfach' : 'FFA',
'Filey' : 'FIL',
'Filton Abbey Wood' : 'FIT',
'Finchley Road & Frognal' : 'FNY',
'Finsbury Park' : 'FPK',
'Finstock' : 'FIN',
'Fishbourne (Sussex)' : 'FSB',
'Fishersgate' : 'FSG',
'Fishguard & Goodwick' : 'FGW',
'Fishguard Harbour' : 'FGH',
'Fiskerton' : 'FSK',
'Fitzwilliam' : 'FZW',
'Five Ways' : 'FWY',
'Fleet' : 'FLE',
'Flimby' : 'FLM',
'Flint' : 'FLN',
'Flitwick' : 'FLT',
'Flixton' : 'FLI',
'Flowery Field' : 'FLF',
'Folkestone Central' : 'FKC',
'Folkestone West' : 'FKW',
'Ford' : 'FOD',
'Forest Gate' : 'FOG',
'Forest Hill' : 'FOH',
'Formby' : 'FBY',
'Forres' : 'FOR',
'Forsinard' : 'FRS',
'Fort Matilda' : 'FTM',
'Fort William' : 'FTW',
'Four Oaks' : 'FOK',
'Foxfield' : 'FOX',
'Foxton' : 'FXN',
'Frant' : 'FRT',
'Fratton' : 'FTN',
'Freshfield' : 'FRE',
'Freshford' : 'FFD',
'Frimley' : 'FML',
'Frinton-on-Sea' : 'FRI',
'Frizinghall' : 'FZH',
'Frodsham' : 'FRD',
'Frome' : 'FRO',
'Fulwell' : 'FLW',
'Furness Vale' : 'FNV',
'Furze Platt' : 'FZP',
}
